version: '3'

services:
  webproxy:
    image: webproxy:finally
    build: ./proxy
    ports:
     - 80:8080
    container_name: webproxy

  helloworld:
    image: dtameka:finally
    build: ./server
    container_name: helloworld
